#!/bin/bash

# First argument: number of runs
#total_run=$9

#Second argument: simulation time (s)
sim_time=$2

echo $numVehiclesPerLane
echo "Running NS3 test"
#6 7 8
for num_nodes in   9 10
#16 17 18 20 25
do
   #for run in $(seq 9 $total_run)
   for run in 1 2 3 4 5 6 7 8 9 10 11 12 13 14 14 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50

   do
       NS_GLOBAL_VALUE="RngRun=$run" ../waf --run "selw-test/selw-test --numVehiclesPerLane=$num_nodes"> test-nd$num_nodes-$run.tr
       #touch ns-3-dev-nd$num_nodes$test-routing.output.csv
   done

done
